---
title: "DDX3X Expression by Tissue Type"
author: "Mason Lynch"
date: "2025-08-05"
output: html_document
---


Setup
```{r}
#Load Packages
library(readr)
library(dplyr)
library(readxl)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(forcats)
library(scales)
library(VennDiagram)

#Set Working Directory
setwd("/Users/mplynch/Desktop/DDX3X TCGA")
```


Load Data
```{r}
#TCGA tpm
tpm_data_df <- as.data.frame(readRDS("TCGA_TPM_summary_cmb.rds"))

#Metadata
metadata <- read_tsv("clinical_PANCAN_patient_with_followup.tsv")
```


Subset and Process Data
```{r}
#Only retain DDX3X tpm data
DDX3X_tpm <- tpm_data_df["DDX3X", ]

#Only keep male metadata samples
metadata_male <- metadata[metadata$gender == "MALE", ]

#Only retain tpm data from male samples
DDX3X_tpm_male <- DDX3X_tpm[, substr(colnames(DDX3X_tpm), 1, 12) %in% metadata_male$bcr_patient_barcode]

#Add cancer type to tpm data
DDX3X_tpm_male <- as.data.frame(t(DDX3X_tpm_male))
DDX3X_tpm_male$patientID <- substr(rownames(DDX3X_tpm_male), 1, 12)
DDX3X_tpm_male <- left_join(DDX3X_tpm_male, metadata_male[, 1:3], by = c("patientID" = "bcr_patient_barcode"))
```


Plot DDX3X Expression by Tissue Type
```{r}
#Plot Results (by copy number)
ggplot(DDX3X_tpm_male, aes(x = fct_reorder(acronym, DDX3X, .fun = median, .desc = TRUE), y = DDX3X)) +
  geom_boxplot(fill = "darkseagreen1", size = .2) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Cancer Type", y = "DDX3X Expression", title = "DDX3X Expression Across Tissue Types")
```




