---
title: "DEAD-Box Helicase Expression vs. LOY DDX3X"
author: "Mason Lynch"
date: "2025-08-11"
output: html_document
---

```{r}
#Install Packages
library(ggplot2)
library(dplyr)
library(readr)
library(stringr)
library(forcats)

#Set Working Directory
setwd("/Users/mplynch/Desktop/DDX3X TCGA")
```


Load in Data
```{r}
#TCGA expression
TCGA_expression <- readRDS("TCGA_TPM_summary_cmb.rds")
TCGA_expression_df <- as.data.frame(TCGA_expression)

#LOY Status
TCGA_LOY <- read.csv("sample_LOY_calls_.7cutoff.csv")

#TCGA metadata
TCGA_metadata <- read_tsv("clinical_PANCAN_patient_with_followup.tsv")

#Define Helicases of Interest (https://www.nature.com/articles/s41590-022-01149-7)
DEAD_box_helicases <- c("DDX4", "DDX42", "DDX41", "DDX46", "DDX23", "DDX53", "DDX43", "DDX17", "DDX5", "DDX19B", "DDX19A", "DDX25", "EIF4A3", "EIF4A2", "EIF4A1", "DDX6", "DDX20", "DDX39B", "DDX39A", "DDX50", "DDX21", "DDX18", "DDX10", "DDX55", "DDX31", "DDX51", "DDX56", "DDX28", "DDX24", "DDX49", "DDX47", "DDX54", "INTS6", "DDX59", "DDX52", "DDX3Y")
```


Filter TPM Dataset
```{r}
#Subset names to only include sample ID
colnames(TCGA_expression_df) <- str_sub(colnames(TCGA_expression_df), 1,16)
TCGA_LOY$Sample_ID <- str_sub(TCGA_LOY$Sample_ID, 1,16)

#Subset to only samples found in segment data (which should include only male samples)
TCGA_expression_df <- TCGA_expression_df[, colnames(TCGA_expression_df) %in% TCGA_LOY$Sample_ID]

#Only DEAD-box Helicase Expression
TCGA_expression_df <- rbind(TCGA_expression_df[DEAD_box_helicases, ], TCGA_expression_df["DDX3X", ], TCGA_expression_df["MKI67", ])

#Remove Low TPM Genes
#TCGA_expression_df <- TCGA_expression_df[rowMeans(TCGA_expression_df) > 10, ]

#Only WTY Samples
TCGA_expression_df_WTY <- TCGA_expression_df[, colnames(TCGA_expression_df) %in% TCGA_LOY$Sample_ID[TCGA_LOY$functional_YCN == "WTY"]]

#Only LOY Samples
TCGA_expression_df_LOY <- TCGA_expression_df[, colnames(TCGA_expression_df) %in% TCGA_LOY$Sample_ID[TCGA_LOY$functional_YCN == "LOY"]]

#Remove NA Samples
TCGA_expression_df_WTY <- na.omit(TCGA_expression_df_WTY)
TCGA_expression_df_LOY <- na.omit(TCGA_expression_df_LOY)
```


Determine correlation and p-Value Of DDX3X and other
```{r}
helicase_lm_summary <- data.frame("correlation_coefficient" = NA, "p_value" = NA)
for (i in 1:(nrow(TCGA_expression_df_LOY)-2)) {
  helicase_model <- cor.test(as.numeric(TCGA_expression_df_LOY[i, ]),
                as.numeric(TCGA_expression_df_LOY["DDX3X", ]))
  
  correlation <-  as.numeric(helicase_model$estimate)
  cor_pval <- helicase_model$p.value
  
  helicase_lm_summary[i, ] <- c(correlation, cor_pval)
}

#Add gene names
helicase_lm_summary$gene_symbol <- rownames(TCGA_expression_df_LOY[!rownames(TCGA_expression_df_LOY) %in% c("DDX3X", "MKI67"), ])

#Transform p-values to corrected p-value
helicase_lm_summary$adjusted_p_value <- p.adjust(helicase_lm_summary$p_value, method = "BH")
```


Plot Results
```{r}
ggplot(helicase_lm_summary, aes(x = fct_reorder(gene_symbol, correlation_coefficient, .fun = mean), y = correlation_coefficient)) +
  geom_col(aes(fill = adjusted_p_value)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Helicase", y = "Correlation Coefficient Helicase ~ DDX3X", title = "TCGA DEAD-Box Helicase Expression Correlation to DDX3X in LOY")
```

Control by Proliferation and Re-Plot
```{r}
helicase_proliferation_lm_summary <- data.frame("correlation_coefficient" = NA, "p_value" = NA)
for (i in 1:(nrow(TCGA_expression_df_LOY)-2)) {
  helicase_model <- cor.test((as.numeric(TCGA_expression_df_LOY[i, ]) / as.numeric(TCGA_expression_df_LOY["MKI67", ])),
                as.numeric(TCGA_expression_df_LOY["DDX3X", ]))
  
  correlation <-  as.numeric(helicase_model$estimate)
  cor_pval <- helicase_model$p.value
  
  helicase_proliferation_lm_summary[i, ] <- c(correlation, cor_pval)
}

#Add gene names
helicase_proliferation_lm_summary$gene_symbol <- rownames(TCGA_expression_df_LOY[!rownames(TCGA_expression_df_LOY) %in% c("DDX3X", "MKI67"), ])

#Transform p-values to corrected p-value
helicase_proliferation_lm_summary$adjusted_p_value <- p.adjust(helicase_proliferation_lm_summary$p_value, method = "BH")

#Plot Proliferation Controlled
ggplot(helicase_proliferation_lm_summary, aes(x = fct_reorder(gene_symbol, correlation_coefficient, .fun = mean), y = correlation_coefficient)) +
  geom_col(aes(fill = adjusted_p_value)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Helicase", y = "PCC Helicase(TPM) / Proliferation ~ DDX3X(TPM)", title = "TCGA DEAD-Box Helicase Expression Correlation to DDX3X in LOY")
```


Calculate and Plot LOY vs. WTY Expression (no controls)
```{r}
#Subset to helicases present in both datasets
TCGA_expression_LOY_helicases <- TCGA_expression_df_LOY[rownames(TCGA_expression_df_LOY) %in% rownames(TCGA_expression_df_WTY), ]
TCGA_expression_WTY_helicases <- TCGA_expression_df_WTY[rownames(TCGA_expression_df_WTY) %in% rownames(TCGA_expression_df_LOY), ]


#Loop through helicases
helicase_upregulation_LOY <- data.frame("helicase" = character(37), "p_value" = numeric(37), "log2fc" = numeric(37))
for (i in 1:(nrow(TCGA_expression_df_LOY)-1)) {
  helicase <- rownames(TCGA_expression_WTY_helicases)[i]
  
  t_test <- t.test(TCGA_expression_LOY_helicases[helicase, ],
                   TCGA_expression_WTY_helicases[helicase, ])
  log2fc <- log2(mean(unlist(TCGA_expression_LOY_helicases[helicase, ])) / mean(unlist(TCGA_expression_WTY_helicases[helicase, ])))
  
  
  helicase_upregulation_LOY$p_value[i] <- t_test$p.value
  helicase_upregulation_LOY$helicase[i] <- helicase
  helicase_upregulation_LOY$log2fc[i] <- log2fc
}


#volcano plot
helicase_upregulation_LOY[helicase_upregulation_LOY$helicase != "DDX3Y", ] %>%
mutate(
  neglog10p = -log10(p_value)
  ) %>%
ggplot(aes(x = log2fc, y = neglog10p)) +
  geom_point(aes(color = p_value < 0.05), size = 3, alpha = 0.7) +
  scale_color_manual(values = c("#6eaff1", "firebrick4")) +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  theme_classic() +
  labs(
    x = "log2 Fold Change (LOY / WTY)",
    y = "-log10(p-value)",
    title = "Helicase Expression LOY vs. WTY (TCGA)"
)

```

