---
title: "TCGA MSI LOY"
author: "Mason Lynch"
date: "2025-12-08"
output: html_document
---

Setup
```{r}
#Install Packages
library(readr)
library(dplyr)
library(readxl)
library(ggplot2)
library(forcats)
library(maftools)
library(GenomicRanges)
library(S4Vectors)
library(tidyr)
library(stringr)
library(ggpubr)
library(ggthemes)

#Set Working Directory
setwd("/Users/mplynch/Desktop/DDX3X TCGA")
```


Load in and Format Data
```{r}
#LOY Calls
LOY_segment_data <- read.csv("/Users/mplynch/Desktop/DDX3X TCGA/sample_LOY_calls_.7cutoff.csv")

#MSISensor Scores from Bailey et al. 2018 (Cell)
MSI_scores <- suppressWarnings(read_excel("/Users/mplynch/Desktop/DDX3X TCGA/MSISensor_TCGA_Ding_2018.xlsx"))
colnames(MSI_scores)[2] <- "MSISensor_score"

#Load in metadata
metadata <- read_tsv("/Users/mplynch/Desktop/DDX3X TCGA/clinical_PANCAN_patient_with_followup.tsv")

#join YCN and MSI status
MSI_YCN <- left_join(LOY_segment_data, MSI_scores, by = c("patientId" = "Participant Barcode"))

#join tissue type
MSI_YCN <- left_join(MSI_YCN, metadata[, 2:3], by = c("patientId" = "bcr_patient_barcode"))

#remove samples without a MSISensor score
MSI_YCN <- MSI_YCN[complete.cases(MSI_YCN$MSISensor_score), ]
```


Measure MSISensor Scores vs. Functional YCN
```{r}
#Subset to functional YCN only samples
MSI_functional_YCN <- MSI_YCN[complete.cases(MSI_YCN$functional_YCN), ]


#t-test analyzing MSISensor scores
print("MSISensor Score t-test")
t.test(MSI_functional_YCN$MSISensor_score ~ MSI_functional_YCN$functional_YCN)


#t-test analyzing MSI as a binary
MSI_WTY_cutoff <- nrow(MSI_functional_YCN[MSI_functional_YCN$functional_YCN == "WTY" & MSI_functional_YCN$MSISensor_score >= 10, ])
MSI_LOY_cutoff <- nrow(MSI_functional_YCN[MSI_functional_YCN$functional_YCN == "LOY" & MSI_functional_YCN$MSISensor_score >= 10, ])
total_WTY <- nrow(MSI_functional_YCN[MSI_functional_YCN$functional_YCN == "WTY", ])
total_LOY <- nrow(MSI_functional_YCN[MSI_functional_YCN$functional_YCN == "LOY", ])

chi_sq_matrix_cutoff <- matrix(c(MSI_LOY_cutoff, total_LOY - MSI_LOY_cutoff,
                          MSI_WTY_cutoff, total_WTY - MSI_WTY_cutoff),
                          nrow = 2, byrow = TRUE)

chisq_result_cutoff <- suppressWarnings(chisq.test(chi_sq_matrix_cutoff, correct = TRUE))

print("MSI Status Binary Chi-Squared Test")
chisq_result_cutoff$p.value

#Log transform MSISensor score
MSI_functional_YCN$log10_MSISensor_score <- log10(MSI_functional_YCN$MSISensor_score + 1)

#Boxplot of MSISensor scores by YCN
ggplot(MSI_functional_YCN, aes(x = functional_YCN,
             y = log10_MSISensor_score)) +
  geom_jitter(aes(color=functional_YCN),
              width = .25,
              alpha = 0.6,
              size = 0.1) +
  geom_boxplot(aes(color = functional_YCN,
                   fill = functional_YCN), width = 0.5, alpha = .5, outliers = F) +
  stat_compare_means(aes(group = functional_YCN),
                     method = "t.test", 
                     label = "p.signif",
                     comparisons = NULL,
                     size = 6,
                     label.x = 1.5) +
  theme_tufte(base_size = 24, base_family = "Arial") +
  scale_color_manual(values = c("#FCAE1E", "#7852A9")) +
  scale_fill_manual(values = c("#FCAE1E", "#7852A9")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none") +
  labs(x = NULL,
       y = "log10(MSISensor Score + 1)",
       title = NULL) -> MSI_plot

#Arrange and save boxplot for figure
MSI_plot <- ggarrange(MSI_plot, ncol = 2)
#ggsave("/Users/mplynch/Desktop/LOY BioRxiv/MSI_YCN_plot.svg", plot = MSI_plot)

#Density plot of MSISensor Scores by YCN
ggplot(MSI_functional_YCN, aes(x = log10_MSISensor_score,
                           fill = functional_YCN,
                           color = functional_YCN)) +
  geom_vline(xintercept = mean(MSI_functional_YCN[MSI_functional_YCN$functional_YCN == "LOY", ]$log10_MSISensor_score),
             linetype = "dashed",
             linewidth = .8,
             color = "#FCAE1E",
             alpha = .5) +
  geom_density(data = MSI_functional_YCN[MSI_functional_YCN$functional_YCN == "LOY", ],
               aes(y = after_stat(scaled)),
               alpha = 0.5,
               outline.type = "upper") +
  geom_vline(xintercept = mean(MSI_functional_YCN[MSI_functional_YCN$functional_YCN == "WTY", ]$log10_MSISensor_score),
             linetype = "dashed",
             linewidth = .8,
             color = "#7852A9",
             alpha = .5) +
  geom_density(data = MSI_functional_YCN[MSI_functional_YCN$functional_YCN == "WTY", ],
               aes(y = after_stat(scaled)),
               alpha = 0.5,
               outline.type = "upper") +
  scale_color_manual(values = c("#FCAE1E", "#7852A9")) +
  scale_fill_manual(values = c("#FCAE1E", "#7852A9")) +
  theme_tufte(base_size = 24, base_family = "Arial") +
  theme(legend.position = "none") +
  labs(x = "log10(MSISensor score + 1)",
       y = "Scaled Density",
       title = NULL) -> MSI_density

#Arrange and save boxplot for figure
#ggsave("/Users/mplynch/Desktop/LOY BioRxiv/LOY Correlates Supplement/MSI_YCN_density.svg", plot = MSI_density)
```


Plot MSISensor Scores vs. Functional YCN by Tissue Type
```{r}
#Identify tissue types without both LOY and WTY samples (to be removed from plot)
excluded_tissues <- c("BRCA", "CHOL", "GBM", "PRAD")

#Plot by tissue type
MSI_functional_YCN[!MSI_functional_YCN$acronym %in% excluded_tissues, ] %>%
ggplot(aes(x = acronym,
             y = log2(MSISensor_score),
             color = functional_YCN,
             fill = functional_YCN)) +
  geom_boxplot(width = 0.5,
               alpha = 0.5,
               outlier.shape = NA,
               position = position_dodge(width = 0.9)) + 
  theme_classic() +
  scale_color_manual(values = c("steelblue4", "skyblue")) +
  scale_fill_manual(values = c("steelblue4", "skyblue")) +
  labs(x = "Tissue Type",
       y = "log2(MSISensor Score)",
       title = "MSISensor Score vs Functional YCN by Tissue Type (TCGA)") +
  stat_compare_means(aes(group = functional_YCN), 
                     method = "wilcox.test", 
                     label = "p.signif",
                     comparisons = NULL) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


Identify Tissues with Significantly Fewer MSI Cases in LOY
```{r}
#identify tissue types of interest
included_tissues <- unique(MSI_functional_YCN$acronym)[!unique(MSI_functional_YCN$acronym) %in% excluded_tissues] 

#Format data frame for analysis
MSI_frequency <- data.frame("acronym" = character(23),
                            "LOY_MSI_frequency" = numeric(23),
                            "LOY_MSI_count" = numeric(23),
                            "LOY_total_count" = numeric(23),
                            "WTY_MSI_frequency" = numeric(23),
                            "WTY_MSI_count" = numeric(23),
                            "WTY_total_count" = numeric(23),
                            "fisher_pvalue" = numeric(23)
)

#Loop to run Fisher's exact test for each tissue type
for (i in seq_along(included_tissues)){
  tissue <- included_tissues[i]
  MSI_samples_tissue <- MSI_functional_YCN[MSI_functional_YCN$acronym == tissue, ]
  
  LOY_MSI_tissue <- sum(MSI_samples_tissue[MSI_samples_tissue$functional_YCN == "LOY", ]$MSISensor_score >= 10)
  WTY_MSI_tissue <- sum(MSI_samples_tissue[MSI_samples_tissue$functional_YCN == "WTY", ]$MSISensor_score >= 10)
  LOY_total_tissue <- sum(MSI_samples_tissue$functional_YCN == "LOY")
  WTY_total_tissue <- sum(MSI_samples_tissue$functional_YCN == "WTY")
  
  fisher_matrix_tissue <- matrix(c(LOY_MSI_tissue, LOY_total_tissue - LOY_MSI_tissue,
                          WTY_MSI_tissue, WTY_total_tissue - WTY_MSI_tissue),
                          nrow = 2, byrow = TRUE)
  fisher_result_tissue <- suppressWarnings(fisher.test(fisher_matrix_tissue))
  
  MSI_frequency$acronym[i] <- tissue
  MSI_frequency$LOY_MSI_frequency[i] <- LOY_MSI_tissue/LOY_total_tissue
  MSI_frequency$LOY_MSI_count[i] <- LOY_MSI_tissue
  MSI_frequency$LOY_total_count[i] <- LOY_total_tissue
  MSI_frequency$WTY_MSI_frequency[i] <- WTY_MSI_tissue/WTY_total_tissue
  MSI_frequency$WTY_MSI_count[i] <- WTY_MSI_tissue
  MSI_frequency$WTY_total_count[i] <- WTY_total_tissue
  MSI_frequency$fisher_pvalue[i] <- fisher_result_tissue$p.value
}

#Identify tissues of interest and plot MSI frequency vs. YCN using the summary table
#In this case, only COAD has more frequent MSI in WTY than LOY
tissue_plot <- "COAD"

tissue_plot_df <- data.frame("functional_YCN" = c("LOY", "WTY"),
           "msi" = c(MSI_frequency$LOY_MSI_count[MSI_frequency$acronym == tissue_plot], MSI_frequency$WTY_MSI_count[MSI_frequency$acronym == tissue_plot]),
           "total" = c(MSI_frequency$LOY_total_count[MSI_frequency$acronym == tissue_plot], MSI_frequency$WTY_total_count[MSI_frequency$acronym == tissue_plot]))

ggplot(tissue_plot_df, aes(fill = functional_YCN,
             x = functional_YCN, y = msi /total)) +
  geom_col(position = "dodge") +
  theme_classic() +
  geom_text(
    aes(label = paste0(msi, "/", total)),
    vjust = -0.3,
    size = 4
  ) +
  annotate(
  "text",
  x = 1.5,
  y = 1.15 * max(tissue_plot_df$msi / tissue_plot_df$total),
  label = paste0("p = ", sprintf("%.4f", MSI_frequency$fisher_pvalue[MSI_frequency$acronym == tissue_plot]), " (Fisher's exact test)"),
  size = 4
) +
  theme(legend.position = "none") +
  scale_color_manual(values = c("steelblue4", "skyblue")) +
  scale_fill_manual(values = c("steelblue4", "skyblue")) +
  labs(x = "Functional YCN",
       y = "MSI Proportion",
       title = paste0(tissue_plot, " MSI Frequency by Functional YCN (MSISensor TCGA)"))
```


Export MSI YCN Combined Data
```{r}
#write.csv(file = "MSISensor_FunctionalYCN_TCGA.csv", mutate(MSI_YCN, MSI_status = ifelse(MSI_YCN$MSISensor_score >= 10, "MSI_High", "MSI_Low")))
```






