---
title: "TMB YCN TCGA"
author: "Mason Lynch"
date: "2026-01-05"
output: html_document
---

Setup
```{r}
#Install Packages
library(readr)
library(dplyr)
library(readxl)
library(ggplot2)
library(ggpubr)
library(ggthemes)

#Set Working Directory
setwd("/Users/mplynch/Desktop/DDX3X TCGA")
```


Load in and Format Data
```{r}
#Load in LOY Calls
LOY_segment_data <- read.csv("/Users/mplynch/Desktop/DDX3X TCGA/sample_LOY_calls_.7cutoff.csv")

#Load in metadata
metadata <- read_tsv("/Users/mplynch/Desktop/DDX3X TCGA/clinical_PANCAN_patient_with_followup.tsv")

#Load in TMB calls
TMB <- read_tsv("/Users/mplynch/Desktop/DDX3X TCGA/mutation-load_updated.tsv")

#join YCN and TMB
TMB_YCN <- left_join(LOY_segment_data, TMB, by = c("patientId" = "Patient_ID"))

#join tissue type
TMB_YCN <- left_join(TMB_YCN, metadata[, 2:3], by = c("patientId" = "bcr_patient_barcode"))

#remove samples without TMB calls or functional_YCN calls
TMB_YCN <- TMB_YCN[complete.cases(TMB_YCN$`Silent per Mb`) & complete.cases(TMB_YCN$`Non-silent per Mb`) & complete.cases(TMB_YCN$functional_YCN), ]
```


Measure TMB vs. Functional YCN
```{r}
#Calculate pooled TMB statistic
TMB_YCN$pooled_per_Mb <- TMB_YCN$`Silent per Mb` + TMB_YCN$`Non-silent per Mb`

#Remove samples with no calculated TMB
TMB_YCN <- TMB_YCN[!TMB_YCN$pooled_per_Mb == 0, ]

#t-test analyzing Silent/Non-Silent TMB
print("Pooled Mutation Burden t-test")
t.test(TMB_YCN$pooled_per_Mb ~ TMB_YCN$functional_YCN)

#Log transform TMB
TMB_YCN$log10_TMB <- log10(TMB_YCN$pooled_per_Mb + 1)

#Plot Silent/Non-Silent TMB by YCN
ggplot(TMB_YCN, aes(x = functional_YCN,
             y = log10_TMB)) +
  geom_jitter(aes(color=functional_YCN),
              width = .25,
              alpha = 0.6,
              size = 0.1) +
  geom_boxplot(aes(color = functional_YCN,
                   fill = functional_YCN), width = 0.5, alpha = .5, outliers = F) +
  stat_compare_means(aes(group = functional_YCN),
                     method = "t.test", 
                     label = "p.signif",
                     comparisons = NULL,
                     size = 6,
                     label.x = 1.5) +
  theme_tufte(base_size = 24, base_family = "Arial") +
  scale_color_manual(values = c("#FCAE1E", "#7852A9")) +
  scale_fill_manual(values = c("#FCAE1E", "#7852A9")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none") +
  labs(x = NULL,
       y = "log10(Mutations per Mb + 1)",
       title = NULL) -> TMB_plot

#Arrange and save plot for figure
TMB_plot <- ggarrange(TMB_plot, ncol = 2)
#ggsave("/Users/mplynch/Desktop/LOY BioRxiv/TMB_YCN_plot.svg", plot = TMB_plot)

#Create density plot of TMB by YCN
ggplot(TMB_YCN, aes(x = log10_TMB,
                           fill = functional_YCN,
                           color = functional_YCN)) +
  geom_vline(xintercept = mean(TMB_YCN[TMB_YCN$functional_YCN == "LOY", ]$log10_TMB),
             linetype = "dashed",
             linewidth = .8,
             color = "#FCAE1E",
             alpha = .5) +
  geom_density(data = TMB_YCN[TMB_YCN$functional_YCN == "LOY", ],
               aes(y = after_stat(scaled)),
               alpha = 0.5,
               outline.type = "upper") +
  geom_vline(xintercept = mean(TMB_YCN[TMB_YCN$functional_YCN == "WTY", ]$log10_TMB),
             linetype = "dashed",
             linewidth = .8,
             color = "#7852A9",
             alpha = .5) +
  geom_density(data = TMB_YCN[TMB_YCN$functional_YCN == "WTY", ],
               aes(y = after_stat(scaled)),
               alpha = 0.5,
               outline.type = "upper") +
  scale_color_manual(values = c("#FCAE1E", "#7852A9")) +
  scale_fill_manual(values = c("#FCAE1E", "#7852A9")) +
  theme_tufte(base_size = 24, base_family = "Arial") +
  theme(legend.position = "none") +
  labs(x = "log10(Mutations per Mb + 1)",
       y = "Scaled Density",
       title = NULL) -> TMB_density

#Arrange and save boxplot for figure
#ggsave("/Users/mplynch/Desktop/LOY BioRxiv/LOY Correlates Supplement/TMB_YCN_density.svg", plot = TMB_density)
```


Plot MSISensor Scores vs. Functional YCN by Tissue Type
```{r}
#Identify tissue types without both LOY and WTY samples (to be removed from plot)
excluded_tissues <- c("BRCA", "CHOL", "GBM", "PRAD")

#Plot by tissue type
TMB_YCN[!TMB_YCN$acronym %in% excluded_tissues, ] %>%
ggplot(aes(x = acronym,
             y = log2(pooled_per_Mb),
             color = functional_YCN,
             fill = functional_YCN)) +
  geom_boxplot(width = 0.5,
               alpha = 0.5,
               outlier.shape = NA,
               position = position_dodge(width = 0.9)) + 
  theme_classic() +
  scale_color_manual(values = c("steelblue4", "skyblue")) +
  scale_fill_manual(values = c("steelblue4", "skyblue")) +
  labs(x = "Tissue Type",
       y = "Mutations / Mb",
       title = "Tumor Mutation Burden vs Functional YCN by Tissue Type (TCGA)") +
  stat_compare_means(aes(group = functional_YCN), 
                     method = "wilcox.test", 
                     label = "p.signif",
                     comparisons = NULL) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

Export TMB YCN Data
```{r}
#write.csv(file = "TMB_YCN_TCGA.csv", TMB_YCN[, c(2,5,6,11,12)])
```







