---
title: "YCN Aneuploidy Score TCGA"
author: "Mason Lynch"
date: "2026-04-01"
output: html_document
---

Setup
```{r}
#Load Packages
library(readr)
library(dplyr)
library(readxl)
library(ggplot2)
library(tidyr)
library(stringr)
library(ggpubr)
library(ggthemes)
library(ggridges)

#Load YCN calls
TCGA_LOY <- read.csv("/Users/mplynch/Desktop/DDX3X TCGA/sample_LOY_calls_.7cutoff.csv")

#Load aneuploigy score calls
TCGA_aneuploidy <- read_xlsx("/Users/mplynch/Desktop/DDX3X TCGA/Aneuploidy_Score_Taylor_2018_CancerCell.xlsx")
```


Join YCN with Aneuploidy Data and Plot
```{r}
#Clean aneuploidy scores dataframe
colnames(TCGA_aneuploidy) <- TCGA_aneuploidy[1, ]
TCGA_aneuploidy <- TCGA_aneuploidy[-1, ]
colnames(TCGA_aneuploidy)[3] <- "AneuploidyScore"
TCGA_aneuploidy <- TCGA_aneuploidy %>%
  mutate(AneuploidyScore = as.numeric(AneuploidyScore)) %>%
  mutate(Genome_doublings = as.numeric(Genome_doublings))

#Join relevant data and subset to samples with complete data
YCN_aneuploidy <- TCGA_aneuploidy %>%
  mutate(patientId = substr(Sample, 1, 12)) %>%
  select(c("patientId", "AneuploidyScore", "Genome_doublings")) %>%
  left_join(TCGA_LOY, by = "patientId") %>%
  filter(complete.cases(functional_YCN))

#Run t-test (for figure we will use actual p-value not stars)
t.test(YCN_aneuploidy[YCN_aneuploidy$functional_YCN == "WTY", ]$AneuploidyScore,
       YCN_aneuploidy[YCN_aneuploidy$functional_YCN == "LOY", ]$AneuploidyScore,
       alternative = "two.sided")

#Boxplot of aneuploidy score by YCN
ggplot(YCN_aneuploidy, aes(x = functional_YCN,
             y = AneuploidyScore)) +
  geom_jitter(aes(color=functional_YCN),
              width = .25,
              alpha = 0.6,
              size = 0.1) +
  geom_boxplot(aes(color = functional_YCN,
                   fill = functional_YCN), width = 0.5, alpha = .5, outliers = F) +
  stat_compare_means(aes(group = functional_YCN),
                     method = "t.test", 
                     label = "p.signif",
                     comparisons = NULL,
                     size = 6,
                     label.x = 1.5) +
  scale_color_manual(values = c("#FCAE1E", "#7852A9")) +
  scale_fill_manual(values = c("#FCAE1E", "#7852A9")) +
  theme_tufte(base_size = 24, base_family = "Arial") +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = NULL,
       y = "Aneuploidy Score",
       title = NULL) -> aneuploidy_boxplot

#Adjust and save boxplot for figure
aneuploidy_boxplot <- ggarrange(aneuploidy_boxplot, ncol = 2)
#ggsave("/Users/mplynch/Desktop/LOY BioRxiv/aneuploidy_YCN_plot.svg", plot = aneuploidy_plot)

#Density plot of aneuploidy score by YCN
ggplot(YCN_aneuploidy, aes(x = AneuploidyScore,
                           fill = functional_YCN,
                           color = functional_YCN)) +
  geom_vline(xintercept = mean(YCN_aneuploidy[YCN_aneuploidy$functional_YCN == "LOY", ]$AneuploidyScore),
             linetype = "dashed",
             linewidth = .8,
             color = "#FCAE1E",
             alpha = .5) +
  geom_density(data = YCN_aneuploidy[YCN_aneuploidy$functional_YCN == "LOY", ],
               aes(y = after_stat(scaled)),
               alpha = 0.5,
               outline.type = "upper") +
  geom_vline(xintercept = mean(YCN_aneuploidy[YCN_aneuploidy$functional_YCN == "WTY", ]$AneuploidyScore),
             linetype = "dashed",
             linewidth = .8,
             color = "#7852A9",
             alpha = .5) +
  geom_density(data = YCN_aneuploidy[YCN_aneuploidy$functional_YCN == "WTY", ],
               aes(y = after_stat(scaled)),
               alpha = 0.5,
               outline.type = "upper") +
  scale_color_manual(values = c("#FCAE1E", "#7852A9")) +
  scale_fill_manual(values = c("#FCAE1E", "#7852A9")) +
  theme_tufte(base_size = 24, base_family = "Arial") +
  theme(legend.position = "none") +
  labs(x = "Aneuploidy Score",
       y = "Scaled Density",
       title = NULL) -> aneuploidy_density

#Adjust and save boxplot for figure
#ggsave("/Users/mplynch/Desktop/LOY BioRxiv/LOY Correlates Supplement/aneuploidy_YCN_density.svg", plot = aneuploidy_density)
```






